apiVersion: v1
kind: ConfigMap
metadata:
  name: capstone-app-config
  namespace: application
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  MONGODB_HOST: "mongodb.application.svc.cluster.local"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "capstone"
  LOG_LEVEL: "Information"
