apiVersion: v1
kind: Secret
metadata:
  name: capstone-app-secret
  namespace: application
type: Opaque
stringData:
  MONGODB_USERNAME: "appuser"
  MONGODB_PASSWORD: "apppassword123"
  JWT_SECRET: "your-super-secret-jwt-key-here"
