apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-postgresql-secret
  namespace: devops-tools
type: Opaque
stringData:
  postgresql-password: "sonarqube123"
  postgresql-postgres-password: "postgres123"
